maj

diff --git a/lib/install b/lib/install
--- a/lib/install
+++ b/lib/install
@@ -8,12 +8,18 @@ fi
 aptitude update > /dev/null
 aptitude install -y libudev-dev libcurl4-openssl-dev pcscd pcsc-tools > /dev/null
 
-if [ $? -ne 0]
+if [ $? -ne 0 ]
 then
     echo "An error occured while installing packages."
     exit 1;
 fi
 
+( cd pcsc-lite-1.8.8 && ./configure --prefix=/usr && make && make install ) 
+if [ $? -ne 0 ]
+then
+    echo "An error occured: pcsc-lite-1.8.8"
+    exit 1;
+fi
 
 ( cd globalplatform-6.0.0 && ./configure --prefix=/usr && make && make install )
 if [ $? -ne 0 ]
@@ -36,12 +42,6 @@ then
     exit 1;
 fi
 
-( cd pcsc-lite-1.8.8 && ./configure --prefix=/usr && make && make install ) 
-if [ $? -ne 0 ]
-then
-    echo "An error occured: pcsc-lite-1.8.8"
-    exit 1;
-fi
 
 ( cd syncapi_lnx-1.5.0 && ./install -prefix /usr ) 
 if [ $? -ne 0 ]
